services:
  debian:
    build: ./requirements/mariadb
    hostname: mariadb
    image: debian-image
    container_name: debian-demo
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
    networks:
      - inception-net
    restart: always
  nginx:
    build: ./requirements/nginx
    hostname: nginx
    image: nginx
    container_name: nginx
    networks:
      - inception-net
    ports:
      - "80:80"
      - "443:443"

networks:
  inception-net:
    driver: bridge

volumes:
  mariadb:
    driver_opts:
      type: "none"
      o: bind
      device: "/Users/nonthakornchencharatmatha/Dev/42bangkok/inception/data/mariadb"
