services:
  db:
    build: ./requirements/mariadb
    hostname: mariadb
    image: debian-image
    container_name: debian-mariadb
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
    networks:
      - inception-net
    restart: always
  nginx:
    build: ./requirements/nginx
    hostname: nginx
    image: nginx
    container_name: nginx
    networks:
      - inception-net
    ports:
      - "9000:9000"
      - "8000:8000"
  wordpress:
    build: ./requirements/wordpress
    hostname: debian-wordpress
    image: wordpress
    container_name: debian-wordpress
    # depends_on:
    #   - db
    networks:
      - inception-net
    volumes:
      - wordpress:/var/lib/mysql
    ports:
      - "7000:7000"
    restart: always

networks:
  inception-net:
    driver: bridge

volumes:
  mariadb:
    driver_opts:
      type: "none"
      o: bind
      device: "/home/nchencha/Documents/onsite/inception/data"
  wordpress:
    driver_opts:
      type: "none"
      o: bind
      device: "/home/nchencha/Documents/onsite/inception/data"
